# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ionagamed/stuff/soft/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/ionagamed/stuff/soft/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ionagamed/stuff/code/projects/huffman-volkfm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ionagamed/stuff/code/projects/huffman-volkfm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ionagamed/stuff/soft/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ionagamed/stuff/soft/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ionagamed/stuff/code/projects/huffman-volkfm/CMakeFiles /home/ionagamed/stuff/code/projects/huffman-volkfm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ionagamed/stuff/code/projects/huffman-volkfm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named huffman

# Build rule for target.
huffman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 huffman
.PHONY : huffman

# fast build rule for target.
huffman/fast:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/build
.PHONY : huffman/fast

engines/huffman-2/deflate.o: engines/huffman-2/deflate.cpp.o

.PHONY : engines/huffman-2/deflate.o

# target to build an object file
engines/huffman-2/deflate.cpp.o:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/deflate.cpp.o
.PHONY : engines/huffman-2/deflate.cpp.o

engines/huffman-2/deflate.i: engines/huffman-2/deflate.cpp.i

.PHONY : engines/huffman-2/deflate.i

# target to preprocess a source file
engines/huffman-2/deflate.cpp.i:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/deflate.cpp.i
.PHONY : engines/huffman-2/deflate.cpp.i

engines/huffman-2/deflate.s: engines/huffman-2/deflate.cpp.s

.PHONY : engines/huffman-2/deflate.s

# target to generate assembly for a file
engines/huffman-2/deflate.cpp.s:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/deflate.cpp.s
.PHONY : engines/huffman-2/deflate.cpp.s

engines/huffman-2/tree-build.o: engines/huffman-2/tree-build.cpp.o

.PHONY : engines/huffman-2/tree-build.o

# target to build an object file
engines/huffman-2/tree-build.cpp.o:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree-build.cpp.o
.PHONY : engines/huffman-2/tree-build.cpp.o

engines/huffman-2/tree-build.i: engines/huffman-2/tree-build.cpp.i

.PHONY : engines/huffman-2/tree-build.i

# target to preprocess a source file
engines/huffman-2/tree-build.cpp.i:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree-build.cpp.i
.PHONY : engines/huffman-2/tree-build.cpp.i

engines/huffman-2/tree-build.s: engines/huffman-2/tree-build.cpp.s

.PHONY : engines/huffman-2/tree-build.s

# target to generate assembly for a file
engines/huffman-2/tree-build.cpp.s:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree-build.cpp.s
.PHONY : engines/huffman-2/tree-build.cpp.s

engines/huffman-2/tree-serialize.o: engines/huffman-2/tree-serialize.cpp.o

.PHONY : engines/huffman-2/tree-serialize.o

# target to build an object file
engines/huffman-2/tree-serialize.cpp.o:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree-serialize.cpp.o
.PHONY : engines/huffman-2/tree-serialize.cpp.o

engines/huffman-2/tree-serialize.i: engines/huffman-2/tree-serialize.cpp.i

.PHONY : engines/huffman-2/tree-serialize.i

# target to preprocess a source file
engines/huffman-2/tree-serialize.cpp.i:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree-serialize.cpp.i
.PHONY : engines/huffman-2/tree-serialize.cpp.i

engines/huffman-2/tree-serialize.s: engines/huffman-2/tree-serialize.cpp.s

.PHONY : engines/huffman-2/tree-serialize.s

# target to generate assembly for a file
engines/huffman-2/tree-serialize.cpp.s:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree-serialize.cpp.s
.PHONY : engines/huffman-2/tree-serialize.cpp.s

engines/huffman-2/tree.o: engines/huffman-2/tree.cpp.o

.PHONY : engines/huffman-2/tree.o

# target to build an object file
engines/huffman-2/tree.cpp.o:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree.cpp.o
.PHONY : engines/huffman-2/tree.cpp.o

engines/huffman-2/tree.i: engines/huffman-2/tree.cpp.i

.PHONY : engines/huffman-2/tree.i

# target to preprocess a source file
engines/huffman-2/tree.cpp.i:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree.cpp.i
.PHONY : engines/huffman-2/tree.cpp.i

engines/huffman-2/tree.s: engines/huffman-2/tree.cpp.s

.PHONY : engines/huffman-2/tree.s

# target to generate assembly for a file
engines/huffman-2/tree.cpp.s:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/tree.cpp.s
.PHONY : engines/huffman-2/tree.cpp.s

engines/huffman-2/util.o: engines/huffman-2/util.cpp.o

.PHONY : engines/huffman-2/util.o

# target to build an object file
engines/huffman-2/util.cpp.o:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/util.cpp.o
.PHONY : engines/huffman-2/util.cpp.o

engines/huffman-2/util.i: engines/huffman-2/util.cpp.i

.PHONY : engines/huffman-2/util.i

# target to preprocess a source file
engines/huffman-2/util.cpp.i:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/util.cpp.i
.PHONY : engines/huffman-2/util.cpp.i

engines/huffman-2/util.s: engines/huffman-2/util.cpp.s

.PHONY : engines/huffman-2/util.s

# target to generate assembly for a file
engines/huffman-2/util.cpp.s:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-2/util.cpp.s
.PHONY : engines/huffman-2/util.cpp.s

engines/huffman-old/HuffmanArchive.o: engines/huffman-old/HuffmanArchive.cpp.o

.PHONY : engines/huffman-old/HuffmanArchive.o

# target to build an object file
engines/huffman-old/HuffmanArchive.cpp.o:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-old/HuffmanArchive.cpp.o
.PHONY : engines/huffman-old/HuffmanArchive.cpp.o

engines/huffman-old/HuffmanArchive.i: engines/huffman-old/HuffmanArchive.cpp.i

.PHONY : engines/huffman-old/HuffmanArchive.i

# target to preprocess a source file
engines/huffman-old/HuffmanArchive.cpp.i:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-old/HuffmanArchive.cpp.i
.PHONY : engines/huffman-old/HuffmanArchive.cpp.i

engines/huffman-old/HuffmanArchive.s: engines/huffman-old/HuffmanArchive.cpp.s

.PHONY : engines/huffman-old/HuffmanArchive.s

# target to generate assembly for a file
engines/huffman-old/HuffmanArchive.cpp.s:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-old/HuffmanArchive.cpp.s
.PHONY : engines/huffman-old/HuffmanArchive.cpp.s

engines/huffman-old/HuffmanDearchive.o: engines/huffman-old/HuffmanDearchive.cpp.o

.PHONY : engines/huffman-old/HuffmanDearchive.o

# target to build an object file
engines/huffman-old/HuffmanDearchive.cpp.o:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-old/HuffmanDearchive.cpp.o
.PHONY : engines/huffman-old/HuffmanDearchive.cpp.o

engines/huffman-old/HuffmanDearchive.i: engines/huffman-old/HuffmanDearchive.cpp.i

.PHONY : engines/huffman-old/HuffmanDearchive.i

# target to preprocess a source file
engines/huffman-old/HuffmanDearchive.cpp.i:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-old/HuffmanDearchive.cpp.i
.PHONY : engines/huffman-old/HuffmanDearchive.cpp.i

engines/huffman-old/HuffmanDearchive.s: engines/huffman-old/HuffmanDearchive.cpp.s

.PHONY : engines/huffman-old/HuffmanDearchive.s

# target to generate assembly for a file
engines/huffman-old/HuffmanDearchive.cpp.s:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/engines/huffman-old/HuffmanDearchive.cpp.s
.PHONY : engines/huffman-old/HuffmanDearchive.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/huffman.dir/build.make CMakeFiles/huffman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... huffman"
	@echo "... engines/huffman-2/deflate.o"
	@echo "... engines/huffman-2/deflate.i"
	@echo "... engines/huffman-2/deflate.s"
	@echo "... engines/huffman-2/tree-build.o"
	@echo "... engines/huffman-2/tree-build.i"
	@echo "... engines/huffman-2/tree-build.s"
	@echo "... engines/huffman-2/tree-serialize.o"
	@echo "... engines/huffman-2/tree-serialize.i"
	@echo "... engines/huffman-2/tree-serialize.s"
	@echo "... engines/huffman-2/tree.o"
	@echo "... engines/huffman-2/tree.i"
	@echo "... engines/huffman-2/tree.s"
	@echo "... engines/huffman-2/util.o"
	@echo "... engines/huffman-2/util.i"
	@echo "... engines/huffman-2/util.s"
	@echo "... engines/huffman-old/HuffmanArchive.o"
	@echo "... engines/huffman-old/HuffmanArchive.i"
	@echo "... engines/huffman-old/HuffmanArchive.s"
	@echo "... engines/huffman-old/HuffmanDearchive.o"
	@echo "... engines/huffman-old/HuffmanDearchive.i"
	@echo "... engines/huffman-old/HuffmanDearchive.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

